### ISSUE TITLE
hardcoded wandb username

### ISSUE THREAD

**Issue by stas00** [tshrjn/Finetune-QA#1]
Came here from https://github.com/PyTorchLightning/pytorch-lightning, the code won't run as it hardcodes creator's wandb username/entity:
```
python main.py --gpus 1 --qa_model distilroberta-base --workers 20 --bs 5 --max_epochs 10
[...]
<transformers.tokenization_roberta.RobertaTokenizerFast object at 0x7f3ad04f5ad0>
wandb: Tracking run with wandb version 0.9.2
wandb: Run data is saved locally in wandb/run-20200706_233437-3sbo0kxn
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
wandb: ERROR Launch exception: Permission denied to access nlp/qa/3sbo0kxn
wandb: ERROR To disable wandb syncing set WANDB_MODE=dryrun
wandb: ERROR W&B process (PID 10015) did not respond
wandb: ERROR W&B process failed to launch, see: wandb/debug.log
```
one needs to edit `main.py`and replace: `entity='nlp'` in:

    wandb_logger = WandbLogger(project='qa', entity='nlp', ...)

with `entity='YOUR WANDB USERNAME'`.

And, of course, if you haven't used wandb yet, you need to create an account first and get the API key.

I, of course, realize that perhaps this is just an example code, so it was never supposed to be runable by others as is... in which case please ignore this issue.

**Comment by tshrjn** [comment]
Thanks for raising this, should be fixed now.
